name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install -y make
        sudo apt-get install -y gcc-arm-none-eabi
        sudo apt-get install -y binutils-arm-none-eabi
        sudo apt-get install -y libnewlib-arm-none-eabi
    - name: Build test
      run: make test

